version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
    labels: ["dependencies"]
    groups:
      minor:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
