version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
    labels: ["dependencies"]
    ignore:
      - dependency-name: "org.jetbrains.kotlin:*"
      - dependency-name: "org.jetbrains.kotlin.*"
      - dependency-name: "org.jetbrains.kotlinx:*"
    groups:
      minor:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
